### ISSUE TITLE
Don't working in windows

### ISSUE THREAD

**Issue by felipecesr** [adamwalzer/vscode-scss-lint#12]
I installed the gem and plugin but it didn't work in my vscode, what is it? My OS is Windows 10.

**Comment by donni106** [comment]
Which gem version are you using?
Did you install the gem globally?

**Comment by felipecesr** [comment]
I installed with the suggested command "gem install scss_lint -v 0.49.0"

**Comment by felipecesr** [comment]
I am using the same as the recommended documentation, 0.49.0. Yes, I installed globally.

**Comment by adamwalzer** [comment]
Hey @felipecesr if you run scss-lint in the terminal what do you get?

**Comment by Mr-Chilly** [comment]
Same issue here!

Scss-lint runs fine in terminal. Infact I have a pre-commit hook that fires and throws errors. 

I get (obvious) scss errors : 

![capture](https://user-images.githubusercontent.com/5287204/29174591-a7792466-7dde-11e7-9a76-b3fac1462956.PNG)

Please note, there are 3 errors, but nothing next to scss-lint!

I've also (weirdly) only got sass as a language, rather than scss.

Brand new install of vscode on windows 10

**Comment by adamwalzer** [comment]
Ok. I think we can solve this. What directory do you run scss-lint from in your terminal, what code do you actually execute, and what is the exact output? I think it's possible I'm making some assumptions about how those things work that is specific to Mac. I would love it if I could fix these issues and make the extension work everywhere. (Anyone know if it works in linux?)

**Comment by Mr-Chilly** [comment]
Sure :-)

`scss-lint` is the core command, I run it from project root, which is actually:

E:\BitBucketProjects\someAwesomeProject

scss-lint version : 0.50.3

**Comment by adamwalzer** [comment]
This is going to be a tough one for me to solve without a Windows computer. I can get a VM, but if we have any Windows developers out there that'd like to take a stab at it, that'd be great!

**Comment by adamwalzer** [comment]
I'm not entirely sure but I'm guessing it may have something to do with the paths using `\` instead of `/` or perhaps some of the packages we use like `exec` or `findParentDir`.

**Comment by Mr-Chilly** [comment]
I'm a dev with a windows machine ;-) 

ok, so looking at it - you're right about the slashes, but that is only half the problem... I've had to hard code my workspace path in (not sure how to fix this)

`const dir = ('c:\\Users\\ME\\Desktop' || '') + '/';`

then when trying to build the command up, we do indeed have / or \ issues:

`const startingDir =  doc.fileName.substring(0, doc.fileName.lastIndexOf('\\'));` Not sure how we fix these going forward mind you...

Building on the command more, I had to `${configFileDir + '\\.scss-lint.yml'}` as configFileDir seemed to be missing the slash (I ended up with `desktop.scss-lint.yml`)

and boom! we've got some scss lint info consoling back! 

After this - we have line.reduce block, finding the index of `[E]` or `[W]` - I think the regex is the issue here, as I've got an exception further down suggesting `info` is null. I'm pretty crap with regex and it's late - so that's a tomorrow job!

More than happy to get you more real bug info and try and get you a PR - But I'll definitely need your help to make this cross-OS

**Comment by Mr-Chilly** [comment]
DOUBLE BOOM!

that regex didn't account for some weird whitespace at the start and end of `line` 👍 

`line = line.replace(/^\s\s*/, '').replace(/\s\s*$/, '');`


![capture](https://user-images.githubusercontent.com/5287204/29196364-af0405b4-7e2b-11e7-986e-96ed7c8453df.PNG)

Ok, so that's three issues (Workspace, Slashes, Regex), any ideas on the best way forward for getting this usable on both OS's?


Also, I have noticed they are only showing as warnings - that doesn't seem right to me (although it's the default .yml so not 100% sure). I'll look more tomorrow :-)

**Comment by adamwalzer** [comment]
Nice I like it. If you make a PR I can fiddle with it to try to get it work on Mac and then we can check to make sure it still works on Windows as well and then merge this.

**Comment by adamwalzer** [comment]
This should be resolved in version 0.0.18. Let me know if it works or does not work for you.
