### ISSUE TITLE
.scss-lint.yml from root not used

### ISSUE THREAD

**Issue by euheny** [adamwalzer/vscode-scss-lint#26]
Hello. MacOs. Latest VS Code, latest plugin. .scss-lint.yml from project root not loaded and linter use default config.

**Comment by donni106** [comment]
Did it work before? Do you have set a config directory?

```
// The directory where to find the .scss-lint.yml file
"scssLint.configDir": ""
```

For me it is working without, `.scss-lint.yml` in root of my apps.

**Comment by euheny** [comment]
Its my first try with VSC and i try make config similar to webstorm.

**Comment by adamwalzer** [comment]
@euheny thanks for reporting the issue. I can try to look more into this sometime this week.

**Comment by adamwalzer** [comment]
@euheny I'm unable to reproduce this issue. Can you please tell me more about your setup? Maybe I'll be able to reproduce this issue if we can more closely reproduce your setup. Also, what happens if you run scss-lint via the command line? It's worth noting that if there is an error in your .scss-lint.yml file the extension will attempt to resolve your lints using the default rather than your .scss-lint.yml since it can't use your .scss-lint.yml.

**Comment by adamwalzer** [comment]
Ok. I'm going to assume this issue is resolved. Feel free to let me know if it is not. Thanks!
